---
title: "Untitled"
author: "Kim Gyeong-min"
date: "2024-04-14"
output: html_document
---
# 모형 진단
## Race data
```{r}
rm( list = ls() )
url = 'http://www.statsci.org/data/general/hills.txt'
races.table = read.table( url, header = TRUE, sep = "\t" )
plot(races.table[,-1], col = "orange")

n = nrow( races.table )
p = 2 

y = matrix( races.table$Time )
X = cbind( "(intercept)" = rep( 1, n ),
           "distance" = races.table$Distance,
           "climb" = races.table$Climb )
beta_hat = solve( t(X) %*% X ) %*% t(X) %*% y
data.frame( beta_hat )
```

# Coefficient Table
```{r}
y_hat = X %*% beta_hat 
resid = y - y_hat 
SSE = sum( resid^2 )

sigma2_hat = SSE / ( n - ( p + 1 ))
Sigma_hat = sigma2_hat * solve( t(X) %*% X )

se.beta_hats = sqrt(diag( Sigma_hat ))
t.value = rep(0, 3)
for (i in 1:3){
  t.value[i] = beta_hat[i] / se.beta_hats[i]
}

p.value = 2 * pt(q = abs(t.value), df = n - ( p + 1 ), lower.tail = FALSE )

coef_table = data.frame( "Estimate" = beta_hat,
                         "Std.Error" = se.beta_hats,
                         t.value,
                         p.value = round( p.value, 4) )

coef_table
```

# R^2와 adjusted R^2
```{r}
SST = sum( ( y - mean(y))^2 )
SSR = SST - SSE

R2 = SSR / SST 
adjusted_R2 = 1 - (SSE / ( n - ( p + 1 ))) / (SST / (n - 1 ))

data.frame( R2, adjusted_R2 )
```

# Internally Studentized residuals   
```{r}
H = X %*% solve( t(X) %*% X ) %*% t(X) 

Internal_resi = resid / sqrt(sigma2_hat * (1 - diag(H)))

plot(resid, Internal_resi)
```








# Externally Studentized residuals   
```{r}
H = X %*% solve( t(X) %*% X ) %*% t(X) 

Exter_resid = rep( 0, n )
for( i in 1:n ){
  y_tilde = matrix( y[-i] ) ##
  X_tilde = X[-i, ]
  
  beta_hat_tilde = solve( t( X_tilde ) %*% X_tilde ) %*% t( X_tilde ) %*% y_tilde
  resid_tilde = y_tilde - X_tilde %*% beta_hat_tilde
  SSE_tilde = sum( resid_tilde^2 )
  sigma2_hat_tilde = SSE_tilde / ( ( n - 1 ) - ( p + 1) )
  
  Exter_resid[i] = resid[i] / sqrt( sigma2_hat_tilde*( 1 - H[i, i] ) )
}

plot( resid, Exter_resid )

data.frame( resid, Internal_resi, Exter_resid )
```














